-   id: sync-claude-code-sessions
    name: Sync Claude Code Sessions
    description: Sync Claude Code session files to the repository
    entry: cc-sync-session sync
    additional_dependencies: ["cli:cc-sync-session"]
    language: rust 
    pass_filenames: false
    always_run: true
    stages: [pre-commit]

